### ISSUE TITLE
Error in creating valley_mesh 

### ISSUE THREAD

**Issue by kensukename2** [jonschwenk/RivGraph#13] opened 2020-04-30 17:11 UTC
Hi. I keep getting error in valley_mesh creation like this:

line 806, in valleyline_mesh
if cs[check_pts[0]] - cs[keep_pts[-1]] > bufferdist:
IndexError: index -20744 is out of bounds for axis 0 with size 13160.

I've tried changing smoothing and buffer parameters, but no luck. I'll try to take a deeper look, but in the mean time any help is appreciated. 

Thank you in advance!

**Comment by jonschwenk** [comment] 2020-04-30 17:14
Hey Kensuke,

Please provide the necessary input files and code required for me to reproduce this error. Otherwise I can't really offer any advice.

**Comment by kensukename2** [comment] 2020-04-30 17:39
Hi Jon,

This zip file should contains the mask image and the code that I am using. Please let me know if anything else is needed!

Thanks!

[githun_issue.zip](https://github.com/jonschwenk/RivGraph/files/4560111/githun_issue.zip)

**Comment by kensukename2** [comment] 2020-05-07 21:16
Hi Jon, 

It seems that if the channel is purely single-thread, the code doesn't run. That is, the channel needs to have at least one multi-threads structure within the reach. To get it work, I have been adding fake secondary channel, but I would not like to do that...

I am hoping to use PyRis to get metrics such as width and eBI, we well as centerline for further analysis, for both single-thread and multi-threads channels. 

Is this feasible? If so, which part of the code needs to be modified?

Thanks in advance! 
Kensuke

**Comment by jonschwenk** [comment] 2020-06-11 16:12
Apologies for the delay here, Kensuke. I recently picked this back up and am working on it. You can always remove all but the main channel using the largest_blobs() function in im_utils.

**Comment by jonschwenk** [comment] 2020-06-12 19:30
Hi Kensuke,

I have made major improvements to the valleyline mesh generator that resolve your issues.

Re: multi-threads, there should be no problem at all. I successfully ran your example here (single thread) and the Brahmaputra (very multi-thread) without issue.

Here are the results of your bug:

Valleyline mesh:
![image](https://user-images.githubusercontent.com/14874485/84539009-e9346200-acaf-11ea-97a1-9e8463cb3b84.png)

eBI:
![image](https://user-images.githubusercontent.com/14874485/84539034-f6e9e780-acaf-11ea-92d0-07a583f30eb4.png)
The eBI is one everywhere despite crossing the river multiple times because there are no unique links; i.e. it crosses the same link, so it is only counted once.

Note: you had the wrong exit sides for this binary image. You wanted 'WN' instead of 'WE' as the end of the river exits to the top of the image. I'll be adding some documentation to make this clearer soon.

Please note that your mesh parameters were a little off. Since your input mask is unprojected EPSG:4326, your units of length are in degrees. Therefore, a bufferwidth of 0.5 means your buffer will be 1 degree wide, which is way too large for this reach.

I am uploading my testing script and results [here](url).

Give me an hour and I will update the github and conda packages (note that I've made conda installation very easy). **You should update your RivGraph version to the latest!** There might be a few syntax changes that break your scripts a little, but they're minor and easily fixable.

Closing, but let me know if you still have issues!

**Closed by jonschwenk** 2020-06-12 19:30 UTC
