### ISSUE TITLE
Excessive nodes (+links) remain in final link/node list

### ISSUE THREAD

**Issue by Lvulis** [jonschwenk/RivGraph#10] opened 2020-03-28 20:25 UTC
I have noticed some extra nodes remain especially around islands. This leads to an extra link around those islands. Not sure what may be causing this (maybe spurs near those islands as well). I will look into it more later and if I find anything will post here as well. These should have been removed during the remove spurs call. Data (shoreline, inlet node, nodes/links jsons, skel) is below the examples: 
![image](https://user-images.githubusercontent.com/18738680/77833016-6f043080-70f7-11ea-9f3d-45e77e6d74e8.png)
![image](https://user-images.githubusercontent.com/18738680/77833019-7297b780-70f7-11ea-83db-1445d32e18e2.png)
![image](https://user-images.githubusercontent.com/18738680/77833027-804d3d00-70f7-11ea-8566-622e96901226.png)

Data:
[Yukon_GSW_201407.zip](https://github.com/jonschwenk/RivGraph/files/4397848/Yukon_GSW_201407.zip)

**Comment by jonschwenk** [comment] 2020-03-29 15:50
"It's a feature, not a bug!"

These are called artificial nodes. You can query them with `delta_class_object.nodes['arts']`. Alex suggested they be incorporated long ago, so they've always been in RivGraph. Their inclusion stems from consideration of the topologic metrics--many of the metrics "fail" in cases of parallel links (i.e. two links that start and end at the same node). The solution for this is to place an "artificial node" at the midpoint of the longer of the parallel links. This does not alter the topology at all.

It should not be too hard to craft a function to remove the artificial nodes, and it's been on the back burner for awhile now. I'll add it to the to-do list.

**Comment by Lvulis** [comment] 2020-03-29 18:29
OK - I will keep this in mind, thanks!

**Comment by jonschwenk** [comment] 2020-06-10 23:42
This issue has been resolved and will be included in the next build of RG. The github repo is up to date as of now.

The better approach here was to not add artificial nodes by default, but provide the functionality for the user to do so immediately before computing metrics that required them. The problem with this is that the artificial nodes were ingrained into the directionality algorithms. 

The implemented solution replaces the artificial node directionality algorithms with a new "parallel links" one that effectively does the same thing. It was tested successfully on the Colville but requires further testing on other deltas/braided rivers.

The `add_artificial_nodes()` function is no longer called by default when pruning your network. It can now be called either before or after running directionality algorithms, and will copy as much information to the new artificial links as possible. However, users will need to recompute link lengths and widths after running this--a print statement informs them of this.

**Closed by jonschwenk** 2020-06-10 23:42 UTC
Labels: documentation, good first issue

**Comment by Lvulis** [comment] 2020-06-11 00:56
Great!
